<a target="_blank" href="https://colab.research.google.com/github/ZHAW-ZAV/TSO-FS26-students/blob/main/01_python_basics/01_03_intro_pandas.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

In [1]:
import sys
import os

IN_COLAB = "google.colab" in sys.modules

file_id_co2 = "1XsuqMub8M3SdP50X1MIwAci-lsYS0X9t"
file_id_countries = "17CMqyq43tBbMJ-TId4TH_GF2KskyIUPP"

if IN_COLAB:
    path_to_co2 = "/content/data/co2_emmissions_by_state_2023.csv"
    os.makedirs(os.path.dirname(path_to_co2), exist_ok=True)
    !gdown "https://drive.google.com/uc?id={file_id_co2}" -O "{path_to_co2}"

    path_to_countries = "/content/data/icao_country.json"
    os.makedirs(os.path.dirname(path_to_countries), exist_ok=True)
    !gdown "https://drive.google.com/uc?id={file_id_countries}" -O "{path_to_countries}"
else:
    import gdown

    url = f"https://drive.google.com/uc?id={file_id_co2}"
    path_to_co2 = "data/co2_emmissions_by_state_2023.csv"
    os.makedirs(os.path.dirname(path_to_co2), exist_ok=True)
    gdown.download(url, path_to_co2, quiet=False)

    url = f"https://drive.google.com/uc?id={file_id_countries}"
    path_to_countries = "data/icao_country.json"
    os.makedirs(os.path.dirname(path_to_countries), exist_ok=True)
    gdown.download(url, path_to_countries, quiet=False)

Downloading...
From: https://drive.google.com/uc?id=1XsuqMub8M3SdP50X1MIwAci-lsYS0X9t
To: /Users/wate/Documents/GitHub/TSO-FS26-students/01_python_basics/data/co2_emmissions_by_state_2023.csv
100%|██████████| 22.3k/22.3k [00:00<00:00, 39.3MB/s]
Downloading...
From: https://drive.google.com/uc?id=17CMqyq43tBbMJ-TId4TH_GF2KskyIUPP
To: /Users/wate/Documents/GitHub/TSO-FS26-students/01_python_basics/data/icao_country.json
100%|██████████| 6.48k/6.48k [00:00<00:00, 12.9MB/s]

The code above loads the data, don't modify.

---------------

***Notebook starts here***

# Introduction to Pandas


## Importing Pandas

In [2]:
import pandas as pd

## Reading Data

In [3]:
# You can read all kinds of files with pandas, not just csv,
# but also excel, json, etc. with pd.read_excel, pd.read_json
co2 = pd.read_csv(path_to_co2)

## Exploring Data

In [4]:
print(f"The DataFrame has {len(co2)} rows.")
print(f"The columns in the DataFrame are: {co2.columns}")

The DataFrame has 517 rows.
The columns in the DataFrame are: Index(['YEAR', 'MONTH', 'STATE_NAME', 'STATE_CODE', 'CO2_QTY_TONNES', 'TF',
       'NOTE'],
      dtype='object')

In [5]:
# Let's take a look at the first few rows
co2.head()

,YEAR,MONTH,STATE_NAME,STATE_CODE,CO2_QTY_TONNES,TF,NOTE
0,2023,1,ALBANIA,LA,18498.33075,1440,False
1,2023,1,ARMENIA,UD,35730.17280,1702,False
2,2023,1,AUSTRIA,LO,178321.12065,11355,False
3,2023,1,BELGIUM,EB,366972.22530,10419,False
4,2023,1,BOSNIA AND HERZEGOVINA,LQ,8112.63100,744,False

In [6]:
# Let's take a look at the last few rows
co2.tail()

     YEAR  MONTH      STATE_NAME STATE_CODE  CO2_QTY_TONNES     TF   NOTE
512  2023     12           SPAIN         LE    1.311217e+06  60117  False
513  2023     12          SWEDEN         ES    1.690412e+05  14277  False
514  2023     12     SWITZERLAND         LS    4.377819e+05  18610  False
515  2023     12         TÜRKIYE         LT    1.340713e+06  49498  False
516  2023     12  UNITED KINGDOM         EG    2.715303e+06  84312   True

In [7]:
# data types of the columns
co2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 517 entries, 0 to 516
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   YEAR            517 non-null    int64
 1   MONTH           517 non-null    int64
 2   STATE_NAME      517 non-null    object
 3   STATE_CODE      517 non-null    object
 4   CO2_QTY_TONNES  517 non-null    float64
 5   TF              517 non-null    int64
 6   NOTE            517 non-null    bool
dtypes: bool(1), float64(1), int64(3), object(2)
memory usage: 24.9+ KB

In [8]:
# Some descriptive statistics
co2.describe()

         YEAR       MONTH  CO2_QTY_TONNES             TF
count   517.0  517.000000    5.170000e+02     517.000000
mean   2023.0    6.500967    3.769603e+05   17240.518375
std       0.0    3.452123    6.407115e+05   25051.991003
min    2023.0    1.000000    4.914000e-01       1.000000
25%    2023.0    4.000000    2.792721e+04    1878.000000
50%    2023.0    7.000000    1.047142e+05    5369.000000
75%    2023.0    9.000000    3.460312e+05   18739.000000
max    2023.0   12.000000    3.213562e+06  108445.000000

In [9]:
# Let's see the unique values in the "STATE_NAME" column
co2["STATE_NAME"].unique()

array(['ALBANIA', 'ARMENIA', 'AUSTRIA', 'BELGIUM',
       'BOSNIA AND HERZEGOVINA', 'BULGARIA', 'CANARY ISLANDS', 'CROATIA',
       'CYPRUS', 'CZECHIA', 'DENMARK', 'ESTONIA', 'FINLAND', 'FRANCE',
       'GEORGIA', 'GERMANY', 'GREECE', 'HUNGARY', 'ICELAND', 'IRELAND',
       'ITALY', 'KOSOVO', 'LATVIA', 'LITHUANIA', 'LUXEMBOURG', 'MALTA',
       'MOLDOVA, REPUBLIC OF', 'MONACO', 'MONTENEGRO', 'NETHERLANDS',
       'NORTH MACEDONIA', 'NORWAY', 'POLAND', 'PORTUGAL', 'ROMANIA',
       'SERBIA', 'SLOVAKIA', 'SLOVENIA', 'SPAIN', 'SWEDEN', 'SWITZERLAND',
       'TÜRKIYE', 'UNITED KINGDOM', 'LIECHTENSTEIN'], dtype=object)

In [10]:
# How many unique values are there in the "STATE_NAME" column?
len(co2["STATE_NAME"].unique())

44

In [11]:
# How many values are there per "STATE_NAME"?
co2["STATE_NAME"].value_counts()

STATE_NAME
ALBANIA                   12
ARMENIA                   12
LUXEMBOURG                12
MALTA                     12
MOLDOVA, REPUBLIC OF      12
MONACO                    12
MONTENEGRO                12
NETHERLANDS               12
NORTH MACEDONIA           12
NORWAY                    12
POLAND                    12
PORTUGAL                  12
ROMANIA                   12
SERBIA                    12
SLOVAKIA                  12
SLOVENIA                  12
SPAIN                     12
SWEDEN                    12
SWITZERLAND               12
TÜRKIYE                   12
UNITED KINGDOM            12
LITHUANIA                 12
LATVIA                    12
KOSOVO                    12
DENMARK                   12
AUSTRIA                   12
BELGIUM                   12
BOSNIA AND HERZEGOVINA    12
BULGARIA                  12
CANARY ISLANDS            12
CROATIA                   12
CYPRUS                    12
CZECHIA                   12
ESTONIA                   12
ITALY                     12
FINLAND                   12
FRANCE                    12
GEORGIA                   12
GERMANY                   12
GREECE                    12
HUNGARY                   12
ICELAND                   12
IRELAND                   12
LIECHTENSTEIN              1
Name: count, dtype: int64

## Filtering and Slicing Data

In [12]:
# classical approach
co2_ch = co2[co2["STATE_NAME"] == "SWITZERLAND"]
co2_ch

     YEAR  MONTH   STATE_NAME STATE_CODE  CO2_QTY_TONNES     TF   NOTE
40   2023      1  SWITZERLAND         LS    383834.25460  17594  False
83   2023      2  SWITZERLAND         LS    354366.44420  17298  False
126  2023      3  SWITZERLAND         LS    404369.38775  19110  False
169  2023      4  SWITZERLAND         LS    424398.75740  18931  False
212  2023      5  SWITZERLAND         LS    438069.13345  20117  False
255  2023      6  SWITZERLAND         LS    438934.97660  20489  False
299  2023      7  SWITZERLAND         LS    490834.04860  21729  False
342  2023      8  SWITZERLAND         LS    482763.56815  21112  False
385  2023      9  SWITZERLAND         LS    465660.48880  21047  False
428  2023     10  SWITZERLAND         LS    471511.22090  20796  False
471  2023     11  SWITZERLAND         LS    396065.21130  16389  False
514  2023     12  SWITZERLAND         LS    437781.91105  18610  False

In [13]:
# using query()
co2_country = co2.query("STATE_NAME == 'SWITZERLAND'")
co2_country

     YEAR  MONTH   STATE_NAME STATE_CODE  CO2_QTY_TONNES     TF   NOTE
40   2023      1  SWITZERLAND         LS    383834.25460  17594  False
83   2023      2  SWITZERLAND         LS    354366.44420  17298  False
126  2023      3  SWITZERLAND         LS    404369.38775  19110  False
169  2023      4  SWITZERLAND         LS    424398.75740  18931  False
212  2023      5  SWITZERLAND         LS    438069.13345  20117  False
255  2023      6  SWITZERLAND         LS    438934.97660  20489  False
299  2023      7  SWITZERLAND         LS    490834.04860  21729  False
342  2023      8  SWITZERLAND         LS    482763.56815  21112  False
385  2023      9  SWITZERLAND         LS    465660.48880  21047  False
428  2023     10  SWITZERLAND         LS    471511.22090  20796  False
471  2023     11  SWITZERLAND         LS    396065.21130  16389  False
514  2023     12  SWITZERLAND         LS    437781.91105  18610  False

In [14]:
# with query, you can use variables and complex expressions
country = "ESTONIA"
co2_country = co2.query("STATE_NAME == @country and MONTH <= 6")
co2_country

     YEAR  MONTH STATE_NAME STATE_CODE  CO2_QTY_TONNES    TF   NOTE
11   2023      1    ESTONIA         EE     13156.97610  1435  False
54   2023      2    ESTONIA         EE     12265.13665  1342  False
97   2023      3    ESTONIA         EE     15355.40020  1641  False
140  2023      4    ESTONIA         EE     14733.77515  1568  False
183  2023      5    ESTONIA         EE     17480.33660  1896  False
226  2023      6    ESTONIA         EE     17160.05470  1800  False

In [15]:
# show only the columns we are interested in
#
# note the nested square brackets. The first one is to
# access the columns of the dataframe, e.g. co2["STATE_NAME"].
# The second one creates a list, e.g. ["STATE_NAME", "MONTH", "CO2_QTY_TONNES"].
co2[["STATE_NAME", "MONTH", "CO2_QTY_TONNES"]]

                 STATE_NAME  MONTH  CO2_QTY_TONNES
0                   ALBANIA      1    1.849833e+04
1                   ARMENIA      1    3.573017e+04
2                   AUSTRIA      1    1.783211e+05
3                   BELGIUM      1    3.669722e+05
4    BOSNIA AND HERZEGOVINA      1    8.112631e+03
..                      ...    ...             ...
512                   SPAIN     12    1.311217e+06
513                  SWEDEN     12    1.690412e+05
514             SWITZERLAND     12    4.377819e+05
515                 TÜRKIYE     12    1.340713e+06
516          UNITED KINGDOM     12    2.715303e+06

[517 rows x 3 columns]

## Aggregating and Sorting Data

In [16]:
print(f"Total CO2 emissions: {co2['CO2_QTY_TONNES'].sum()}")
print(f"Mean CO2 emissions: {co2['CO2_QTY_TONNES'].mean()}")

# let's display this neatly
print(f"Total CO2 emissions: {co2['CO2_QTY_TONNES'].sum():.0f}")
print(f"Mean CO2 emissions: {co2['CO2_QTY_TONNES'].mean():.1f}")

Total CO2 emissions: 194888478.06594998
Mean CO2 emissions: 376960.30573684716
Total CO2 emissions: 194888478
Mean CO2 emissions: 376960.3

### Grouping data, single aggregation

In [17]:
# group by country and sum the CO2 emissions

# this is a bit more advanced, let's break it down
# 1. group by country: co2.groupby("STATE_NAME")
# 2. select the column we are interested in: ["CO2_QTY_TONNES"]
# 3. sum the values: .sum()

co2_country = co2.groupby("STATE_NAME")["CO2_QTY_TONNES"].sum()
co2_country

STATE_NAME
ALBANIA                   3.293914e+05
ARMENIA                   4.763148e+05
AUSTRIA                   2.568658e+06
BELGIUM                   4.983545e+06
BOSNIA AND HERZEGOVINA    1.328787e+05
BULGARIA                  7.153200e+05
CANARY ISLANDS            3.564486e+06
CROATIA                   6.234476e+05
CYPRUS                    1.005989e+06
CZECHIA                   1.045479e+06
DENMARK                   2.556152e+06
ESTONIA                   1.882184e+05
FINLAND                   2.085232e+06
FRANCE                    2.040482e+07
GEORGIA                   5.199006e+05
GERMANY                   2.676138e+07
GREECE                    4.631251e+06
HUNGARY                   1.033389e+06
ICELAND                   4.862220e+05
IRELAND                   3.198638e+06
ITALY                     1.362850e+07
KOSOVO                    1.760861e+05
LATVIA                    4.033560e+05
LIECHTENSTEIN             4.914000e-01
LITHUANIA                 3.932189e+05
LUXEMBOURG                1.779039e+06
MALTA                     4.679135e+05
MOLDOVA, REPUBLIC OF      1.816314e+05
MONACO                    2.935863e+02
MONTENEGRO                1.204150e+05
NETHERLANDS               9.873388e+06
NORTH MACEDONIA           1.570689e+05
NORWAY                    2.596338e+06
POLAND                    3.611087e+06
PORTUGAL                  5.411971e+06
ROMANIA                   1.401467e+06
SERBIA                    5.498005e+05
SLOVAKIA                  1.560030e+05
SLOVENIA                  9.050871e+04
SPAIN                     1.722617e+07
SWEDEN                    2.313917e+06
SWITZERLAND               5.188589e+06
TÜRKIYE                   1.832419e+07
UNITED KINGDOM            3.352681e+07
Name: CO2_QTY_TONNES, dtype: float64

In [18]:
# same as above, but sorted
#
# Hint: you can split the code into multiple lines to make it more readable,
#       just wrap the code in parentheses

co2_country = (
    co2.groupby("STATE_NAME")["CO2_QTY_TONNES"].sum().sort_values(ascending=False)
)
co2_country

STATE_NAME
UNITED KINGDOM            3.352681e+07
GERMANY                   2.676138e+07
FRANCE                    2.040482e+07
TÜRKIYE                   1.832419e+07
SPAIN                     1.722617e+07
ITALY                     1.362850e+07
NETHERLANDS               9.873388e+06
PORTUGAL                  5.411971e+06
SWITZERLAND               5.188589e+06
BELGIUM                   4.983545e+06
GREECE                    4.631251e+06
POLAND                    3.611087e+06
CANARY ISLANDS            3.564486e+06
IRELAND                   3.198638e+06
NORWAY                    2.596338e+06
AUSTRIA                   2.568658e+06
DENMARK                   2.556152e+06
SWEDEN                    2.313917e+06
FINLAND                   2.085232e+06
LUXEMBOURG                1.779039e+06
ROMANIA                   1.401467e+06
CZECHIA                   1.045479e+06
HUNGARY                   1.033389e+06
CYPRUS                    1.005989e+06
BULGARIA                  7.153200e+05
CROATIA                   6.234476e+05
SERBIA                    5.498005e+05
GEORGIA                   5.199006e+05
ICELAND                   4.862220e+05
ARMENIA                   4.763148e+05
MALTA                     4.679135e+05
LATVIA                    4.033560e+05
LITHUANIA                 3.932189e+05
ALBANIA                   3.293914e+05
ESTONIA                   1.882184e+05
MOLDOVA, REPUBLIC OF      1.816314e+05
KOSOVO                    1.760861e+05
NORTH MACEDONIA           1.570689e+05
SLOVAKIA                  1.560030e+05
BOSNIA AND HERZEGOVINA    1.328787e+05
MONTENEGRO                1.204150e+05
SLOVENIA                  9.050871e+04
MONACO                    2.935863e+02
LIECHTENSTEIN             4.914000e-01
Name: CO2_QTY_TONNES, dtype: float64

In [19]:
# How many values are there per "STATE_NAME"?
# We did this already with this:
# co2["STATE_NAME"].value_counts()
#
# An alternative approach is to use groupby and count the number of rows
# in each group. This is done with the size() function.
print(co2.groupby("STATE_NAME").size())

# or with groupby and count()
print(co2.groupby("STATE_NAME")["STATE_NAME"].count())

STATE_NAME
ALBANIA                   12
ARMENIA                   12
AUSTRIA                   12
BELGIUM                   12
BOSNIA AND HERZEGOVINA    12
BULGARIA                  12
CANARY ISLANDS            12
CROATIA                   12
CYPRUS                    12
CZECHIA                   12
DENMARK                   12
ESTONIA                   12
FINLAND                   12
FRANCE                    12
GEORGIA                   12
GERMANY                   12
GREECE                    12
HUNGARY                   12
ICELAND                   12
IRELAND                   12
ITALY                     12
KOSOVO                    12
LATVIA                    12
LIECHTENSTEIN              1
LITHUANIA                 12
LUXEMBOURG                12
MALTA                     12
MOLDOVA, REPUBLIC OF      12
MONACO                    12
MONTENEGRO                12
NETHERLANDS               12
NORTH MACEDONIA           12
NORWAY                    12
POLAND                    12
PORTUGAL                  12
ROMANIA                   12
SERBIA                    12
SLOVAKIA                  12
SLOVENIA                  12
SPAIN                     12
SWEDEN                    12
SWITZERLAND               12
TÜRKIYE                   12
UNITED KINGDOM            12
dtype: int64
STATE_NAME
ALBANIA                   12
ARMENIA                   12
AUSTRIA                   12
BELGIUM                   12
BOSNIA AND HERZEGOVINA    12
BULGARIA                  12
CANARY ISLANDS            12
CROATIA                   12
CYPRUS                    12
CZECHIA                   12
DENMARK                   12
ESTONIA                   12
FINLAND                   12
FRANCE                    12
GEORGIA                   12
GERMANY                   12
GREECE                    12
HUNGARY                   12
ICELAND                   12
IRELAND                   12
ITALY                     12
KOSOVO                    12
LATVIA                    12
LIECHTENSTEIN              1
LITHUANIA                 12
LUXEMBOURG                12
MALTA                     12
MOLDOVA, REPUBLIC OF      12
MONACO                    12
MONTENEGRO                12
NETHERLANDS               12
NORTH MACEDONIA           12
NORWAY                    12
POLAND                    12
PORTUGAL                  12
ROMANIA                   12
SERBIA                    12
SLOVAKIA                  12
SLOVENIA                  12
SPAIN                     12
SWEDEN                    12
SWITZERLAND               12
TÜRKIYE                   12
UNITED KINGDOM            12
Name: STATE_NAME, dtype: int64

### Grouping data, multiple aggregations

In [20]:
# you can also use the .agg() method to apply multiple functions at once
# for example, we want the sum of the total traffic (TF) and the sum and mean of the CO2 emissions
#
# 1. group by country: co2.groupby("STATE_NAME")
# 2. use the .agg() method to apply multiple functions at once
#    it takes a dictionary as an argument, where the keys are the column names
#    and the values are the functions to apply
# 3. sort the values by the sum of the CO2 emissions
co2_country = (
    co2.groupby("STATE_NAME")
    .agg({"TF": "sum", "CO2_QTY_TONNES": ["sum", "mean"]})
    .sort_values(by=("CO2_QTY_TONNES", "sum"), ascending=False)
)
co2_country

                             TF CO2_QTY_TONNES
                            sum            sum          mean
STATE_NAME
UNITED KINGDOM          1115114   3.352681e+07  2.793901e+06
GERMANY                  954664   2.676138e+07  2.230115e+06
FRANCE                   889669   2.040482e+07  1.700402e+06
TÜRKIYE                  708780   1.832419e+07  1.527016e+06
SPAIN                    865856   1.722617e+07  1.435514e+06
ITALY                    820322   1.362850e+07  1.135708e+06
NETHERLANDS              303796   9.873388e+06  8.227823e+05
PORTUGAL                 251496   5.411971e+06  4.509976e+05
SWITZERLAND              233222   5.188589e+06  4.323825e+05
BELGIUM                  150552   4.983545e+06  4.152954e+05
GREECE                   308838   4.631251e+06  3.859376e+05
POLAND                   226136   3.611087e+06  3.009240e+05
CANARY ISLANDS           214466   3.564486e+06  2.970405e+05
IRELAND                  149426   3.198638e+06  2.665532e+05
NORWAY                   328859   2.596338e+06  2.163615e+05
AUSTRIA                  159975   2.568658e+06  2.140549e+05
DENMARK                  167584   2.556152e+06  2.130127e+05
SWEDEN                   203852   2.313917e+06  1.928264e+05
FINLAND                   98218   2.085232e+06  1.737693e+05
LUXEMBOURG                35856   1.779039e+06  1.482532e+05
ROMANIA                  104412   1.401467e+06  1.167889e+05
CZECHIA                   71332   1.045479e+06  8.712324e+04
HUNGARY                   59378   1.033389e+06  8.611579e+04
CYPRUS                    44848   1.005989e+06  8.383239e+04
BULGARIA                  45274   7.153200e+05  5.961000e+04
CROATIA                   61805   6.234476e+05  5.195396e+04
SERBIA                    44858   5.498005e+05  4.581671e+04
GEORGIA                   25436   5.199006e+05  4.332505e+04
ICELAND                   23217   4.862220e+05  4.051850e+04
ARMENIA                   22119   4.763148e+05  3.969290e+04
MALTA                     31105   4.679135e+05  3.899279e+04
LATVIA                    31156   4.033560e+05  3.361300e+04
LITHUANIA                 29015   3.932189e+05  3.276824e+04
ALBANIA                   25517   3.293914e+05  2.744928e+04
ESTONIA                   20085   1.882184e+05  1.568487e+04
MOLDOVA, REPUBLIC OF      12286   1.816314e+05  1.513595e+04
KOSOVO                    12140   1.760861e+05  1.467384e+04
NORTH MACEDONIA           11624   1.570689e+05  1.308908e+04
SLOVAKIA                  15314   1.560030e+05  1.300025e+04
BOSNIA AND HERZEGOVINA    10819   1.328787e+05  1.107322e+04
MONTENEGRO                12307   1.204150e+05  1.003459e+04
SLOVENIA                  12138   9.050871e+04  7.542392e+03
MONACO                      481   2.935863e+02  2.446552e+01
LIECHTENSTEIN                 1   4.914000e-01  4.914000e-01

## Modifying and Merging DataFrames

In [21]:
# let's say we want to add a column with the CO2 emissions per movement
# we can do this by dividing the CO2 emissions by the total traffic
co2["CO2_PER_TF"] = co2["CO2_QTY_TONNES"] / co2["TF"]
co2.sort_values("CO2_PER_TF", ascending=False)

,YEAR,MONTH,STATE_NAME,STATE_CODE,CO2_QTY_TONNES,TF,NOTE,CO2_PER_TF
455,2023,11,LUXEMBOURG,EL,172653.46140,2745,False,62.897436
498,2023,12,LUXEMBOURG,EL,167603.36420,2707,False,61.914800
67,2023,2,LUXEMBOURG,EL,133687.59010,2437,False,54.857444
110,2023,3,LUXEMBOURG,EL,152097.47975,2874,False,52.921879
24,2023,1,LUXEMBOURG,EL,127278.80010,2421,False,52.572821
...,...,...,...,...,...,...,...,...
113,2023,3,MONACO,LN,18.13455,30,False,0.604485
242,2023,6,MONACO,LN,31.38030,52,False,0.603467
372,2023,9,MONACO,LN,34.32240,57,False,0.602147
27,2023,1,MONACO,LN,10.37610,18,False,0.576450
281,2023,7,LIECHTENSTEIN,LS,0.49140,1,False,0.491400

In [22]:
# let's say we want to add some more information about the countries from another file
# first, load the file. This time it's a json file, so we use pd.read_json
# countries = pd.read_json(path_to_countries)
countries = pd.read_json("data/icao_country.json")
countries.head()

  icao_country country_code
0           AG           SB
1           AN           NR
2           AT           PG
3           AY           PG
4           BG           GL

***See notes on join in the presentation***
```python
import pandas as pd

# Inner Join: Keeps only the rows with keys that are present in both DataFrames.
pd.merge(df_left, df_right, on="id", how="inner")

# Left Join: Keeps all rows from the left DataFrame and adds matching rows from the right DataFrame. Non-matching rows will have NaN values for columns from the right DataFrame.
pd.merge(df_left, df_right, on="id", how="left")    

# Right Join: Keeps all rows from the right DataFrame and adds matching rows from the left DataFrame. Non-matching rows will have NaN values for columns from the left DataFrame.
pd.merge(df_left, df_right, on="id", how="right")   

# Outer Join: Keeps all rows from both DataFrames. Non-matching rows will have NaN values for columns from the other DataFrame.
pd.merge(df_left, df_right, on="id", how="outer")
```

In [24]:
# now we want to add ISO two character country code to our dataframe. Merging two datasets is a common
# operation and is often called a "join" or "merge". For this to work, we need a common column in both
# datasets. In our case, we have the ICAO code in both dataframes. It is the column "STATE_CODE" in
# the co2 dataframe and "icao_country" in the countries dataframe.
# We can use the .merge() method to join the two.
co2_with_countries = co2.merge(
    countries, left_on="STATE_CODE", right_on="icao_country", how="inner"
)
print(
    f"The original dataframe has {len(co2)} rows, the new one has {len(co2_with_countries)}."
)
co2_with_countries.head()

The original dataframe has 517 rows, the new one has 505.

,YEAR,MONTH,STATE_NAME,STATE_CODE,CO2_QTY_TONNES,TF,NOTE,CO2_PER_TF,icao_country,country_code
0,2023,1,ALBANIA,LA,18498.33075,1440,False,12.846063,LA,IR
1,2023,1,ARMENIA,UD,35730.17280,1702,False,20.993051,UD,AM
2,2023,1,AUSTRIA,LO,178321.12065,11355,False,15.704194,LO,AT
3,2023,1,BELGIUM,EB,366972.22530,10419,False,35.221444,EB,BE
4,2023,1,BOSNIA AND HERZEGOVINA,LQ,8112.63100,744,False,10.904074,LQ,BA

In [25]:
# well, it seems that we have fewer rows in the new dataframe. Let's see which countries are missing.

# get the countries in the co2 dataframe
countries1 = co2["STATE_CODE"].unique()

# get the countries in the merged dataframe
countries2 = co2_with_countries["icao_country"].unique()

# find the countries that are in the co2 dataframe but not in the countries dataframe
# this can easily be done with sets, which are a data type in python
missing_countries = set(countries1) - set(countries2)
missing_countries

# let's see the rows where the country is missing
co2.query("STATE_CODE in @missing_countries")

     YEAR  MONTH STATE_NAME STATE_CODE  CO2_QTY_TONNES  TF   NOTE  CO2_PER_TF
27   2023      1     MONACO         LN        10.37610  18  False    0.576450
70   2023      2     MONACO         LN        12.64095  20  False    0.632047
113  2023      3     MONACO         LN        18.13455  30  False    0.604485
156  2023      4     MONACO         LN        25.05825  41  False    0.611177
199  2023      5     MONACO         LN        32.91120  54  False    0.609467
242  2023      6     MONACO         LN        31.38030  52  False    0.603467
286  2023      7     MONACO         LN        39.42855  64  False    0.616071
329  2023      8     MONACO         LN        42.32340  70  False    0.604620
372  2023      9     MONACO         LN        34.32240  57  False    0.602147
415  2023     10     MONACO         LN        21.98700  36  False    0.610750
458  2023     11     MONACO         LN        13.03470  21  False    0.620700
501  2023     12     MONACO         LN        11.98890  18  False    0.666050

In [26]:
# let's try again, this time with a left join
co2_with_countries = co2.merge(
    countries, left_on="STATE_CODE", right_on="icao_country", how="left"
)
print(
    f"The original dataframe has {len(co2)} rows, the new one has {len(co2_with_countries)}."
)
co2_with_countries.head()

The original dataframe has 517 rows, the new one has 517.

,YEAR,MONTH,STATE_NAME,STATE_CODE,CO2_QTY_TONNES,TF,NOTE,CO2_PER_TF,icao_country,country_code
0,2023,1,ALBANIA,LA,18498.33075,1440,False,12.846063,LA,IR
1,2023,1,ARMENIA,UD,35730.17280,1702,False,20.993051,UD,AM
2,2023,1,AUSTRIA,LO,178321.12065,11355,False,15.704194,LO,AT
3,2023,1,BELGIUM,EB,366972.22530,10419,False,35.221444,EB,BE
4,2023,1,BOSNIA AND HERZEGOVINA,LQ,8112.63100,744,False,10.904074,LQ,BA